#include<sys/sem.h>
#include<sys/shm.h>
#include<sys/msg.h>
#include<termios.h>
#include<fcntl.h>
#include<time.h>
#include<stdio.h>
#include<stdlib.h>
#include<dirent.h>
#include<string.h>
#include<unistd.h>
#include<sys/resource.h>
#include<sys/wait.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<sys/time.h>
